#!/bin/bash
set -u

cd $SEAFILE_HOME
exec $SEAFILE_BIN/seafile.sh start &

echo "Waiting 10s before starting watcher script: seafile.sh"
sleep 10

echo "Starting watcher script: seafile.sh"
while true; do
	
	for SEAFILE_PROC in "seafile-control" "ccnet-server" "seaf-server"
	do
		pkill -0 -f "${SEAFILE_PROC}"
		RC=$?
		
		if [ $CONTAINER_DEBUG == "1" ]; then
			echo "checking on ${SEAFILE_PROC}, return: ${RC}"
		fi
		
		if [ $RC != 0 ]; then
			echo "${SEAFILE_PROC} has returned non-zero exit code: ${RC}"
			# TODO call seafile.sh stop
			exit $RC
		fi
		
		sleep 1
    done
	
    sleep 10
done


# #!/bin/sh
# echo Starting seafile...
# ${SEAFILE_INSTALL_DIR}/seafile.sh start
# echo Tailing seafile STDOUT...
# tail -f /proc/`cat ${SEAFILE_INSTALL_DIR}/../pids/seaf-server.pid`/fd/1
# echo seafile closed.